version: '3.8'

services:

  dashboard:
    container_name: reddit-happiness-dashboard
    build: .
    restart: always
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    env_file:
      - .env
    command: streamlit run src/dashboard/app.py --server.port 8501 --server.address 0.0.0.0

  pipeline:
    container_name: reddit-happiness-pipeline
    build: .
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    env_file:
      - .env
    command: python main.py

    tty: true
    stdin_open: true

  scheduler:
    container_name: reddit-happiness-scheduler
    build: .
    restart: always
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    entrypoint: sh -c "
      apt update && apt install -y cron && apt clean;

      echo '0 1 * * 0 python /app/main.py' | crontab -;

      cron -f"

networks:
  default:
    name: reddit_analytics_network